# Exercise Answers {#exercise-answers}

Download all [exercises and data files](exercises/exercises.zip) below as a ZIP archive. The answers are not included in the zip file.

* [01 intro](exercises/01_intro_exercise.Rmd) ([answers](exercises/01_intro_answers.html)): Intro to R, functions, R markdown
* [02 ggplot](exercises/02_ggplot_exercise.Rmd) ([answers](exercises/02_ggplot_answers.html)): Data visualisation
* [03 data](exercises/03_data_exercise.Rmd) ([answers](exercises/03_data_answers.html)): Vectors, tabular data, data import, pipes
* [04 tidyr](exercises/04_tidyr_exercise.Rmd) ([answers](exercises/04_tidyr_answers.html)): Tidy Data
* [05 dplyr](exercises/05_dplyr_exercise.Rmd) ([answers](exercises/05_dplyr_answers.html)): Data wrangling
* [06 joins](exercises/06_joins_exercise.Rmd) ([answers](exercises/06_joins_answers.html)): Data relations
* [07 glm](exercises/07_glm_exercise.Rmd) ([answers](exercises/07_glm_answers.html)): GLM
* [08 functions](exercises/08_func_exercise.Rmd) ([answers](exercises/08_func_answers.html)): Functions and iteration
* [09 simulation](exercises/09_sim_exercise.Rmd) ([answers](exercises/09_sim_answers.html)): Simulation
